// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3aAsuyY8a601VW_Xe_L6FO5zLEOP-tNo',
    appId: '1:806824587137:android:a58bcfa3ad0f59d54b8280',
    messagingSenderId: '806824587137',
    projectId: 'prm-lab-3',
    storageBucket: 'prm-lab-3.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPnWhaW3QrMlK8lcyO8jmes3NW9YJofwc',
    appId: '1:806824587137:ios:60c79e7b5e292f8d4b8280',
    messagingSenderId: '806824587137',
    projectId: 'prm-lab-3',
    storageBucket: 'prm-lab-3.firebasestorage.app',
    androidClientId: '806824587137-fu46vl00r7srpku428i9pmgudnu6bkkt.apps.googleusercontent.com',
    iosClientId: '806824587137-4eg4dt8n7akgjj0m274lj5vbo0aiqv8s.apps.googleusercontent.com',
    iosBundleId: 'xyz.pinace.pinaceWallet',
  );
}
